services:
  e2e:
    build:
      dockerfile: ./dockerfile
    volumes:
      - ./specs:/usr/src/app/specs
    depends_on:
      - reservations
      - auth
      - notifications
      - payments

  reservations:
    image: us-east4-docker.pkg.dev/sleepr-378423/reservations/production
    env_file:
      - ../apps/reservations/.env
    ports:
      - '3000:3000'

  auth:
    image: us-east4-docker.pkg.dev/sleepr-378423/auth/production
    env_file:
      - ../apps/auth/.env
    ports:
      - '3001:3001'

  payments:
    image: us-east4-docker.pkg.dev/sleepr-378423/payments/production
    env_file:
      - ../apps/payments/.env
    ports:
      - '3003:3003'

  notifications:
    image: us-east4-docker.pkg.dev/sleepr-378423/notifications/production
    env_file:
      - ../apps/notifications/.env
    ports:
      - '3004:3004'
